// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistencia.Context;

namespace Persistencia.Migrations
{
    [DbContext(typeof(EFContext))]
    partial class EFContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Modelo.Entidades.Ocorrencia", b =>
                {
                    b.Property<long?>("OcorrenciaId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Criticidade");

                    b.Property<DateTime>("DataHora");

                    b.Property<long>("Numero_Ocorrencia");

                    b.Property<string>("Solucao");

                    b.Property<int>("Status");

                    b.Property<string>("Titulo")
                        .IsRequired();

                    b.HasKey("OcorrenciaId");

                    b.ToTable("Ocorrencias");
                });

            modelBuilder.Entity("Modelo.Entidades.Rotina", b =>
                {
                    b.Property<int>("RotinaId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Execucao");

                    b.Property<string>("Nome");

                    b.Property<int>("OrdemDeServico");

                    b.Property<string>("ResponsavelDaRotina");

                    b.HasKey("RotinaId");

                    b.ToTable("Rotinas");
                });

            modelBuilder.Entity("Modelo.Entidades.Servidor", b =>
                {
                    b.Property<long?>("ServidorId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Ambiente");

                    b.Property<string>("Nome")
                        .IsRequired();

                    b.Property<string>("ServidorIp")
                        .IsRequired();

                    b.HasKey("ServidorId");

                    b.ToTable("Servidores");
                });

            modelBuilder.Entity("Modelo.Tabelas.Iteracao", b =>
                {
                    b.Property<long?>("IteracaoId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Assinatura");

                    b.Property<DateTime>("DataHoraIteracao");

                    b.Property<long?>("OcorrenciaId");

                    b.Property<string>("TextoIteracao");

                    b.HasKey("IteracaoId");

                    b.HasIndex("OcorrenciaId");

                    b.ToTable("Iteracoes");
                });

            modelBuilder.Entity("Modelo.Tabelas.Iteracao", b =>
                {
                    b.HasOne("Modelo.Entidades.Ocorrencia", "Ocorrencia")
                        .WithMany("Iteracoes")
                        .HasForeignKey("OcorrenciaId");
                });
#pragma warning restore 612, 618
        }
    }
}
